### ISSUE TITLE
Changing font in theme

### ISSUE THREAD

**Issue by skeskali** [MerryPanda/brackets-theme-spring-light#1]
Hi, 
No matter what font I specify in the preferences, I can't seem to change the default font in this theme. I've tried editing the brackets.json file, but the font stays the same. Thanks for any help you can offer!

**Comment by MerryPanda** [comment]
Hey! It's not a bug, it's a feature ^_^
Well, probably, standard font should be removed... ( it is defined in the theme.spring.light.less
 file)
cheeers

**Comment by skeskali** [comment]
Thanks!

Actually, now that I look at that file, I don't see anything that says 'standard font'. I'm really new to less stylesheet language, so maybe I'm looking for the wrong thing?

**Comment by MerryPanda** [comment]
Hi!
that's the string you are looking for (in the .less file)

.CodeMirror-gutters {font-family:calibri;}

regards

**Comment by MerryPanda** [comment]
force font is removed in a new version
